services:
  mongodb:
    image: mongo:latest
    container_name: ecommerce-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

volumes:
  mongodb_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge