@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGZlMGI5YmEyYWFhYTJlMTU3YTM2NCIsImlhdCI6MTc2MTE0NjI4NCwiZXhwIjoxNzYxMjMyNjg0fQ.DJLuFshP8YcDuoiSqIqQ-Q0g106-BUAYXt_nmixMgdg

### Login user
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "meyer@ejemplo.com",
    "password": "123456"
}

### Get current user profile
GET http://localhost:4000/api/profile/me
Authorization: Bearer {{token}}

### Create a new product
POST http://localhost:4000/api/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Producto de prueba",
    "description": "Este es un producto de prueba",
    "price": 100,
    "stock": 50
}
### delete a product
DELETE http://localhost:4000/api/products/68f8f5bc6cd8812df0751b5f
Authorization: Bearer {{token}}

### get all products
GET http://localhost:4000/api/products