### Get all users
GET http://localhost:4000/api/users

### Get user by ID
DELETE http://localhost:4000/api/users/68dd4cdf3794701c364d8c09


### Register user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "meyer@ejemplo.com",
    "password": "123456",
    "name": "Julian Meyer"
}

### Login user
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "meyer@ejemplo.com",
    "password": "123456"
}

### Get current user profile
GET http://localhost:4000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGZlMGI5YmEyYWFhYTJlMTU3YTM2NCIsImlhdCI6MTc1OTkzNTkzNCwiZXhwIjoxNzYwMDIyMzM0fQ.k588OkE1O79C8Wmic7D6w2Z_Xrg-cBS0KB9umD5Oaro
